variables:
  DEBIAN_FRONTEND: noninteractive
  GIT_SUBMODULE_STRATEGY: recursive

.build: &build
  stage: build
  script:
    - cmake ${BUILD_OPTIONS} -S . -B cmake-build
    - cmake --build cmake-build --config Release -j 8
    - ctest -C Release --test-dir cmake-build --output-on-failure

build:linux:x86:20.04:
  image: ${DOCKER_CACHE}/ubuntu:20.04
  before_script:
    - apt-get update && apt-get install -y git cmake zlib1g-dev
  <<: *build
  tags:
    - linux

build:windows:
  variables:
    BUILD_OPTIONS: "-A x64"
  <<: *build
  tags:
    - windows-10
    - VS2019

build:macos:m1:
  <<: *build
  tags:
    - xcode-13.3.1
    - m1
